### ISSUE TITLE
Improvement/Bug: KeyError raised when invalid topic slug passed to latestposts endpoint.

### ISSUE THREAD

**Issue by re-alejandro-garcia** [weeping-angel/medium-apis#1]
In the [_latestposts.py](https://github.com/weeping-angel/medium-api/blob/main/src/medium_api/_latestposts.py) module line 37 a KeyError is raised when an invalid topic slug is passed to the latestposts endpoint. Since the latestposts endpoint is limited in regards to what values can passed to the topic_slug argument, when an invalid topic slug is passed this results in an error returned by the Medium API which ultimately results in an empty dict being returned at [medium.py](https://github.com/weeping-angel/medium-api/blob/main/src/medium_api/medium.py) line 82. When the `resp['latestposts']` call is made in _latestposts.py this then raises a KeyError which is a rather unhelpful error considering the reason why the error is being raised.

I propose that instead a more meaningful error message be raised in this situation so that users can be better informed in regards to how this error can be avoided. Perhaps an error message similar to the following:

`An error occurred when calling the latestposts endpoint. Please ensure that you have passed a valid topic slug. If you are unsure if the topic slug you are using is valid consider using the topfeeds endpoint instead.`

Alternatively, if the intention is to avoid raising an error then there should be a check to determine if the response dictionary is empty so that the KeyError is not raised.

**Comment by weeping-angel** [comment]
Hey @re-alejandro-garcia, Thank you so much for pointing this out. I'll implement this error handling as soon as possible. I'm also working on other improvements in this python package, so I'll roll out everything at once in the upcoming 0.2.8 version on the PyPI. 

If you're only interested in this specific improvement, I'll resolve and commit it on Github by the weekend. Then, you can download it and directly install it from the source.

Happy coding!

**Comment by weeping-angel** [comment]
Hey, I resolved this issue!

I put a try/except block in the `_latestposts.py` file. Now, it will give a proper error message (same as you suggested above) and instead of failing entirely, it will provide an empty list. So your program won't crash because of one wrong input.

To determine whether you got the result for your input or not (programmatically), simply check the length of the returning list. 

`len(latestposts.ids)==0` or `len(latestposts.articles)==0` means wrong input.

I hope this helps.

If you've any other suggestions, feel free to raise an issue. And thanks again for pointing this out :)
